plugins {
    id 'base'
}

tasks.register('packageAddon', Zip) {
    group = 'build'
    description = 'Build Blender add-on ZIP including compiler JAR'

    dependsOn ':compiler:shadowJar', ':compiler:copyToAddon'

    from('addon') {
        into 'meldr'
    }

    archiveFileName = 'meldr-blender-addon.zip'
    destinationDirectory = file("$buildDir/dist")
}