plugins {
    id 'java'
    id 'antlr'
    id 'application'
    id 'com.gradleup.shadow' version '8.3.9'
}

group = 'org.meldr.compiler'
version = '1.5.0'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

application {
    mainClass = 'org.meldr.compiler.Driver'
}

dependencies {
    antlr ('org.antlr:antlr4:4.13.2')
}

shadowJar {
    archiveBaseName.set("compiler")
    archiveClassifier.set("") // removes '-all' suffix
    mergeServiceFiles()
}

tasks.register('copyToAddon', Copy) {
    dependsOn tasks.named('shadowJar')
    from(tasks.named('shadowJar').get().archiveFile.get().asFile)
    into "$rootDir/addon/"        // root repo add-on folder
    rename { "compiler-${project.version}.jar" }     // rename shadow JAR to canonical name
}
